base_url = "https://vandeefeng.github.io/gitmemo/"
generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
summary_length = 150  # 设置摘要长度，单位为字符
even_title = "Vandee's Memos"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags/top/", name = "Top"},
]
